version: "3.0"
services:
  fortuna:
    image: bot_fortuna
    build:
      context: .
      dockerfile: 'BOT_FORTUNA/Dockerfile'
    container_name: 'BOT_FORTUNA'
    ports:
      - '10601:10601'
    restart: always
    healthcheck:
      test: ["CMD", "perl", "healthcheck.pl", "", "healthchecker", "--botname", "bot_fortuna", "--port", "10601"]
      interval: 60s
      retries: 3
      # start_period: 10s
      timeout: 2s

# networks:
#   default:
#     name: alloxentric.com
