version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - mynetwork

  frontend:
    build:
      context: ./alloxentric
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - mynetwork
    depends_on:
      - backend
  
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin_twa
      KEYCLOAK_ADMIN_PASSWORD: Adm2024.
    ports:
      - "8081:8081"
    command: ["start-dev", "--http-port=8081", "--import-realm"] # Importa realms al inicio
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import  # Monta tu carpeta local con el realm-export.json
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
